services:
  - type: web
    name: rcapex
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: |
      # Install server deps
      npm ci
      # Build client (include dev deps so vite is available)
      cd ../client && npm ci --include=dev && npm run build
      # Copy client build into server/client-dist for production serving
      mkdir -p ../server/client-dist && rm -rf ../server/client-dist/* && cp -r dist/* ../server/client-dist/
      # Back to server
      cd ../server
    startCommand: node src/server.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      # Server port is provided by Render in $PORT automatically
      # Add your runtime secrets below or via Render dashboard
      - key: APEX_BASE
        sync: false
      - key: APEX_USERNAME
        sync: false
      - key: APEX_PASSWORD
        sync: false
      - key: DEFAULT_UNIT
        value: h0zDeGnQIgfY3px
      - key: DEFAULT_DATUM_VON
        value: 2024-10-01T00:00:00Z
      - key: DEFAULT_DATUM_BIS
        value: 2025-05-30T00:00:00Z
      - key: UNIT_EXT_IDS
        value: zaE22GlNK6AZfBc,YytRDIbdYtOVax8,VUmfO9SS3wXt2iB,h0zDeGnQIgfY3px,YtK84kUP26b7bMw,eQnsTZhPu8GPFUm
      # SMTP configuration (set via Render dashboard for persistence)
      - key: SMTP_HOST
        value: smtp.strato.de
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: m.banner@futurestore.shop
      - key: SMTP_DEFAULT_RECIPIENT
        value: olaf.glebsattel@realcore.de, m.banner@realcore.de
      - key: DEBUG_MAIL
        value: "0"
